[scrolling]
history = 0

[shell]
args = ["-d Ubuntu"]
program = "wsl.exe"

[window]
startup_mode = "Maximized"
dynamic_padding = false
decorations = "None"

[window.padding]
x = 20
#y = 20

[font]
size = 11
offset.y = 6
glyph_offset.y = 3

[font.normal]
family = "Iosevka Term"
style = "Extended"

[font.bold]
family = "Iosevka Term"
style = "Bold Extended"

[font.italic]
family = "Iosevka Term"
style = "Italic Extended"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic Extended"

#
## Colors (Solarized Dark)
#
## Default colors
#[colors.primary]
#background = '#002b36'
#foreground = '#839496'
#
## Normal colors
#[colors.normal]
#black   = '#073642'
#red     = '#dc322f'
#green   = '#859900'
#yellow  = '#b58900'
#blue    = '#268bd2'
#magenta = '#d33682'
#cyan    = '#2aa198'
#white   = '#eee8d5'
#
## Bright colors
#[colors.bright]
#black   = '#002b36'
#red     = '#cb4b16'
#green   = '#586e75'
#yellow  = '#657b83'
#blue    = '#839496'
#magenta = '#6c71c4'
#cyan    = '#93a1a1'
#white   = '#fdf6e3'
#
# Colors (Solarized Light)

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#586e75'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[colors]
draw_bold_text_with_bright_colors = false
